Hi <?php echo $this->firstname ?> <?php echo $this->surname ?>,

Pirate Congress 2011 is nearly over, all we need to do is vote! A big thank
you to those that attended or participated remotely in the debate on Saturday
and Sunday, in Sydney. We hope that many more will attend in Melbourne, July
2012.

IMPORTANT, PLEASE READ BEFORE VOTING

There are thirteen (13) motions that need to go to a vote by all members and
there are three (3) positions that are contested and require a vote.

The following link will take you to your voting form. Please DO NOT share this
link with anyone. It is a single use key, and once submitted, you will not be
able to change your vote, so please make your choices carefully.

Voting will open for seven (7) days. Also, please keep in mind that this is a
new system created specifically for elections within this party and has not
been previously used extensively. If there are any problems, or you have
questions regarding your vote, please contact secretary@pirateparty.org.au
with your queries.

<?php echo $this->link ?>


Please take the time to cast your vote. It is very important.


Kind Regards,

The Congress Team

