<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<title>Service Not Found</title>
	<style type="text/css">
		body, html
		{
			font-family: Arial, Verdana;
			font-size: 12px;
			text-align: center;
		}

		a
		{
			display: block;
			margin-top: 50px;
			border: 0px;
			opacity: 0.5;
		}

		a:hover
		{
			opacity: 1;
		}
	</style>
</head>
<body>
	<div style="width: 400px; margin: auto; margin-top: 50px;">
		<h1>PPAU Voting System</h1>
		<p>This is a private system - please keep out unless you have been given a voting key.</p>
		<a href="http://www.pirateparty.org.au/"><img src="http://pirateparty.org.au/themes/theme140/logo.png" width="400" height="103" alt="Pirate Party Australia" /></a>
	</div>
</body>
</html>
