<?php
$this->inlineScript()->captureStart();
?>
// randomly rearrange ul
function rearrange(container)
{
	if(container.length && container.length > 1)
	{
		$j(container).each(function() {
			rearrange(this);
		});
		return;
	}
	var items = $j(container).children();
	items.detach(); // remove existing nodes from DOM
	// randomly select items and add them back in
	while(items.length > 0)
		$j(container).append(items.splice(Math.floor(Math.random()*items.length),1));
}

$j(function() {
	// register validator
	var validate = function() {
		return HardValidate.validate($j('form#vote'))
	}
	PPAUVote.addValidator(validate);

	// rearrange all the election candidates
	rearrange($j('.preferential'));
});
<?php
$this->inlineScript()->captureEnd();
?>

<h2>2011 Pirate Party Congress</h2>

<fieldset>
<legend>Motions carried over from 2010</legend>

<p>As per Article 7, section 3 &mdash; the members will vote on whether to raise the quorum in Article 7, section 1 by an additional 2%. The current quorum is 10%. To vote 'YES' is to increase the quorum for constitutional amendments to 12%. To vote 'NO' causes this clause to lapse.</p>

<div class="multiple">
<label><input type="radio" required="required" name="quorum" value="yes" /> Yes</label>
<label><input type="radio" required="required" name="quorum" value="no" /> No</label>
<label><input type="radio" required="required" name="quorum" value="" /> Abstain</label>
</div>

<hr>

<p><em>Grammatical error in Constitution</em></p>
<p>Motion: To amend the following sentence in Part I to reflect the following:</p>
<blockquote>Overbearing and restrictive private monopolies constructed via regimes of antiquated, unfair and unbalanced laws which prevent the free development of culture and ideas<del>, and</del> are detrimental to financial, economic and cultural outcomes for the citizens of Australia.</blockquote>

<div class="multiple">
<label><input type="radio" required="required" name="grammar" value="yes" /> Yes</label>
<label><input type="radio" required="required" name="grammar" value="no" /> No</label>
<label><input type="radio" required="required" name="grammar" value="" /> Abstain</label>
</div>

<hr>

<p>Motion: To add, in Article 8, under the title Party Secretary, a 6th section, that specifies the following:</p>
<blockquote>6. Briefly minute, or delegate responsibility for minuting,  listing the decisions of meetings of the National Congress and National Council and ensure publication at the earliest possible convenience.</blockquote>

<div class="multiple">
<label><input type="radio" required="required" name="minute" value="yes" /> Yes</label>
<label><input type="radio" required="required" name="minute" value="no" /> No</label>
<label><input type="radio" required="required" name="minute" value="" /> Abstain</label>
</div>

<hr>

<p>Motion: To add, in Article 8, under the title President, a 3rd section, that specifies the following:</p>
<blockquote>3. Co-ordinate the activities of the National Council.</blockquote>

<div class="multiple">
<label><input type="radio" required="required" name="president_coordinate" value="yes" /> Yes</label>
<label><input type="radio" required="required" name="president_coordinate" value="no" /> No</label>
<label><input type="radio" required="required" name="president_coordinate" value="" /> Abstain</label>
</div>

</fieldset>
<fieldset>
<legend>Motions for the Current Congress</legend>

<p><em>Put by: Rodney Serkowski</em></p>
<p>Motion: To add, in the Pirate Party platform Section 2.<em>x</em>, the following:</p>
<blockquote>
<p><strong>2.<em>x</em>. Reform of Democratic Institutions</strong></p>
<p><u>All Levels of Government Should Recognise and Facilitate E-Petitions</u></p>
<p>Petitions are a well established and recognised form of political  participation. In order to broaden political participation  governments at all levels the state should recognise and facilitate electronic petitioning as a legitimate form of participation.</p>

<p><u>Petitions Should Enhance Democratic Participation</u></p>
<p>Recognition of all petitions must have attendant obligations upon the elected government when it reaches a pre-determined quota, which include mandated parliamentary discussion, meetings with petitioners and formal recognition of issues raised within the petition.</p>
</blockquote>

<div class="multiple">
<label><input type="radio" required="required" name="e-petition" value="yes" /> Yes</label>
<label><input type="radio" required="required" name="e-petition" value="no" /> No</label>
<label><input type="radio" required="required" name="e-petition" value="" /> Abstain</label>
</div>

<hr>

<p><em>Put by: Mozart Olbrycht-Palmer</em></p>
<p>Motion: To add, in the Pirate Party platform Section 2.<em>x</em> the following:</p>
<blockquote>
<p><strong>2.<em>x</em>. Open-sourcing of State Funded Software</strong></p>

<p>All software created or commissioned by the government should be open-sourced if paid for by the taxpayers. Open-source software is more valuable to the public than closed, proprietary software: open-source software can be adapted by knowledgeable end-users for additional uses not envisioned by the original creators. Open-source software is also open to inspection by the public, increasing the chances that security issues can be found and resolved quickly, and allowing for a greater degree of transparency in government.</p>
</blockquote>

<div class="multiple">
<label><input type="radio" required="required" name="open_source" value="yes" /> Yes</label>
<label><input type="radio" required="required" name="open_source" value="no" /> No</label>
<label><input type="radio" required="required" name="open_source" value="" /> Abstain</label>
</div>

<hr>

<p><em>Put by: David Haidon</em></p>
<p>Motion: that the Pirate Party adopts <a href="http://dl.dropbox.com/u/7611623/Purple%20PPAU%20Logos.pdf">Purple ("Swatch Option 9")</a> for the official colours.</p>
<p>The current colours are <a href="http://dl.dropbox.com/u/7611623/Blue%20PPAU%20Logos.pdf">Blue ("Swatch Option 5")</a>.</p>
<p><em><strong>Please note:</strong> these colours will appear slightly differently on all monitors, and will print differently. Also note that the colours here are in CYMK, not RGB, meaning they were intended for professional printing and cannot be viewed accurately using a home printer or monitor.</em></p>

<div class="multiple">
<label><input type="radio" required="required" name="purple" value="yes" /> Yes</label>
<label><input type="radio" required="required" name="purple" value="no" /> No</label>
<label><input type="radio" required="required" name="purple" value="" /> Abstain</label>
</div>

<hr>

<p><em>Put by: Simon Frew &amp; David Haidon</em></p>
<p>Motion: To form a campaign committee to prepare materials to promote the Pirate Party and its ideals directly after the Congress. The committee is to prepare materials for O-Week 2012, in order to begin the process of forming Pirate Party Australia clubs.</p>

<div class="multiple">
<label><input type="radio" required="required" name="campaign_committee" value="yes" /> Yes</label>
<label><input type="radio" required="required" name="campaign_committee" value="no" /> No</label>
<label><input type="radio" required="required" name="campaign_committee" value="" /> Abstain</label>
</div>

<hr>

<p><em>Put by: Simon Frew</em></p>
<p>Motion: To produce Pirate Sampler 2 ready for distribution for O-Week 2012 with accompanying torrent and information.</p>

<div class="multiple">
<label><input type="radio" required="required" name="sampler_2" value="yes" /> Yes</label>
<label><input type="radio" required="required" name="sampler_2" value="no" /> No</label>
<label><input type="radio" required="required" name="sampler_2" value="" /> Abstain</label>
</div>

<hr>

<p><em>Put by: David Campbell &amp; Simon Frew</em></p>
<p>Motion: To hold a Pirate Roadshow, hosting workshops on a range of Pirate related issues around the country, including practical demonstrations of anonymising software, circumventing censorship and personal IT security.</p>

<div class="multiple">
<label><input type="radio" required="required" name="roadshow" value="yes" /> Yes</label>
<label><input type="radio" required="required" name="roadshow" value="no" /> No</label>
<label><input type="radio" required="required" name="roadshow" value="" /> Abstain</label>
</div>

<hr>

<p><em>Put by: Liam Pomfret</em></p>
<p>Motion: That the congress endorses the following statement:</p>
<blockquote>
<p>Pirate Party Australia condemns the ongoing patent wars and the destructive effects that it has on the economy and innovation in general.</p>
<p>Patents are not fulfilling the intended purpose for which they were created, to  give small players the protections they need to participate in research  and in the knowledge economy against larger firms who can better afford engaging in legal action and manoeuvres. This can in part be attributed  to the length patents are awarded for remaining unchanged even as  technology has improved at an exponential rate. Whereas historically  inventions may have taken several years to spread around the globe, today inventions can be created, distributed globally and then  superceded several times in a matter of months.</p>
<p>Organisations of all sizes are harmed by this war over patents, as all organisations  must participate in research and development in order to compete in the modern globalised economy. Patents as they stand currently have created a system in which organisations are forced to waste millions of dollars in legal budgets to defend themselves from rivals. Combined with the increasing trend of firms to speculation and hoarding of patents, organisations are now laying claim to increasingly trivial ideas and concepts.</p>
<p>These practices are clearly absurd, and a hinderence to innovation and  economic growth. Ideas are not natural property, and there is no inherent notion or right of ownership in an invention. An idea is part of the greater collective knowledge of society, regardless of if this idea may be an abstract process, business methodology, chemical formulae or a mathematical procedure or algorithm.</p>
</blockquote>

<div class="multiple">
<label><input type="radio" required="required" name="patents" value="yes" /> Yes</label>
<label><input type="radio" required="required" name="patents" value="no" /> No</label>
<label><input type="radio" required="required" name="patents" value="" /> Abstain</label>
</div>
</fieldset>

<fieldset>
<legend>National Council Election</legend>
<p><strong><a target="_blank" href="http://www.pirateparty.org.au/wiki/Congress_2011_Candidate_Statements">Please click here to see the candidate statements</a></strong></p>
<p>The preferential voting system in use for this election is the Condorcet system. Number 
 the candidates from 1 to 3, where 1 is your highest preference and 3 is your lowest. Thank you.</p> 

<p><em>As nobody but David Campbell stood for the position of President, he defaults to this position.</em></p>

<p>Please select your preferences for the position of General Secretary:</p>
<ul class="preferential">
<li><label><input type="number" size="3" name="secretary-frew" min="1" max="3" required="required" />Simon Frew</label></li>
<li><label><input type="number" size="3" name="secretary-haidon" min="1" max="3" required="required" />David Haidon</label></li>
<li><label><input type="number" size="3" name="secretary-molloy" min="1" max="3" required="required" />Brendan Molloy</label></li>
</ul>

<p><em>As nobody but Rodney Serkowski stood for the position of Treasurer, he defaults to this position</em></p>

<p>Please select your preferences for the position of Deputy President:</p>
<ul class="preferential">
<li><label><input type="number" size="3" name="deputy_president-frew" min="1" max="3" required="required" />Simon Frew</label></li>
<li><label><input type="number" size="3" name="deputy_president-haidon" min="1" max="3" required="required" />David Haidon</label></li>
<li><label><input type="number" size="3" name="deputy_president-molloy" min="1" max="3" required="required" />Brendan Molloy</label></li>
</ul>

<p>Please select your preferences for the position of Deputy Secretary:</p>
<ul class="preferential">
<li><label><input type="number" size="3" name="deputy_secretary-frew" min="1" max="3" required="required" />Simon Frew</label></li>
<li><label><input type="number" size="3" name="deputy_secretary-haidon" min="1" max="3" required="required" />David Haidon</label></li>
<li><label><input type="number" size="3" name="deputy_secretary-molloy" min="1" max="3" required="required" />Brendan Molloy</label></li>
</ul>

<p><em>As nobody but Jack Coulter stood for the position of Deputy Treasurer, he defaults to this position.</em></p>

<p><em>As nobody but Alexis Shaw stood for the position of Party Agent, he defaults to this position.</em></p>

<p><em>As nobody but Quentin Taran stood for a position on the Dispute Resolution Council, he defaults to this position.</em></p>

</fieldset>

